version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: >
      /bin/sh -c "
      until pg_isready -h db -U user -d messenger; do
        echo 'Waiting for PostgreSQL...';
        sleep 1;
      done;
      until redis-cli -h redis ping; do
        echo 'Waiting for Redis...';
        sleep 1;
      done;
      echo 'PostgreSQL and Redis are up!';
      alembic upgrade head;
      uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT}
      "
    volumes:
      - ./logs:/app/logs
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  logs: